name: Build & Deploy
on:
  push:
    branches: [ main ]

env:
  as-name: "as-cast"
  rg-name: "rg-cast"

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      sql:
        image: mcr.microsoft.com/mssql/server
        ports:
          - 1433:1433
        env:
          SA_PASSWORD: Your_password123
          ACCEPT_EULA: Y

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --configuration Release --filter "FullyQualifiedName!~AcceptanceTests"
      env:
        ConnectionStrings__DefaultConnection: Server=.;Database=CleanArchitectureDb-Test;User=sa;Password=Your_password123;MultipleActiveResultSets=true;
    - name: Publish
      run: dotnet publish src/WebUI/WebUI.csproj --configuration Release --output website
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: website
        path: /home/runner/work/CleanArchitecture/CleanArchitecture/website/**
        if-no-files-found: error

  deploy-staging:
    needs: build
    
    runs-on: ubuntu-latest

    environment:
      name: staging
      url: ${{ steps.deploywebapp.outputs.webapp-url }}
    
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.8
      with:
        name: website
        path: website

    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy web app
      id: deploywebapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.as-name }}
        slot-name: staging
        package: website

    - name: Logout via Azure CLI
      run: az logout

  deploy-prod:
    needs: deploy-staging

    runs-on: ubuntu-latest

    environment:
      name: prod
      url: ${{ steps.slot_swap.outputs.url }}

    steps:
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Swap Staging and Prod
      id: slot_swap
      run: |
        az webapp deployment slot swap -g ${{ env.rg-name }} -n ${{ env.as-name }} -s staging
        url=$(az webapp show -g ${{ env.rg-name }} -n ${{ env.as-name }} --query "defaultHostName" -o tsv)
        echo "::set-output name=url::https://$url"

    - name: Logout via Azure CLI
      run: az logout
